Module3 task1
htmlacademy-react/1521451-six-cities-5 pull request #6
Opened 2020-10-13 21:18 UTC by AlexandrRumiantsev

2020-10-14 20:58 UTC, DmitryMarkov requested changes
Задание реализовано неоптимальным способом

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +  const CalcRating = (percent) =>{
- функции должны называться с маленькой буквы
- хелперам не место в app.jsx, лучше вынести в отдельный файл и импортировать прямо в компонент

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +      width: percent * 10 * 2 + '%'
зачем возвращать объект?

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +  }
Каждый компонент должен быть в своем файле

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +  }
Зачем?

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +                render={(props)=>{
ты же не используешь тут пропсы, не надо их показывать

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +                  return <Favorites styles={styles}/>
вроде мы уже обсуждали, что лучше использовать css-стили, а не js

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/comments/comments.jsx
> +    data.rating = new FormData(formRef.current).get('rating');
так лучше, конечно, но ref не обязателен для этого, можно просто по именованным полям формы пройтись. К тому же есть ивент, который ты не используешь почти

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/comments/comments.jsx
> +    props.component.state.reviews.push(data);
рановато ты начал это делать, не было в задании

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/comments/comments.jsx
> +    props.component.setState(
вообще, это пишется через this, не знаю, где ты взял такую нотацию...

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/comments/comments.jsx
> +        </label>
похоже на копипасту, можно это упростить

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/comments/comments.jsx
> +    ).isRequired
нет, так дело не пойдет, не надо передавать компонент в качестве пропса

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/main/main.jsx
> +                    <a href={`/offer/`+offer.id}>
надо использовать шаблонные строки а не конкатенацию

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/main/main.jsx
> +                      <img className="place-card__image" src={offer.gallary[0].src} width="260" height="200" alt="Place image"/>
```suggestion
                      <img className="place-card__image" src={offer.gallery[0].src} width="260" height="200" alt="Place image"/>
```

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/main/main.jsx
> +                        <span className="place-card__price-text">&#47;&nbsp;{offer.prices[1]}</span>
зачем night в мок? он не бедут приходить с сервера в таком виде

2020-10-14 20:58 UTC, DmitryMarkov commented on src/components/main/main.jsx
> +                  { (offer.premium) ? PremiumTemplate('place-card__mark') : ''}
можно сделать деструктуризацию, так как везде повторяется `offer.`

2020-10-14 20:58 UTC, DmitryMarkov commented on src/mocks/offers.js
> +    meeter: {
скорее это `host`

2020-10-14 20:58 UTC, DmitryMarkov commented on src/mocks/offers.js
> +  },
разметка не будет приходить с сервера и это опасно вставлять чужую разметку в код

2020-10-14 20:58 UTC, DmitryMarkov commented on src/shapes/comments-props.js
> +  revews: PropTypes.array.isRequired
```suggestion
  reviews: PropTypes.array.isRequired
```

2020-10-14 22:08 UTC, AlexandrRumiantsev commented on src/components/app/app.jsx
> +  const CalcRating = (percent) =>{
Создам src/helpers/CalcRating.js и внутри нужную функцию, тогда куда её импортировать? Есть ли смысл в Аpp компонент, что бы потом через пропсы передавать? Или сразу импортировать в нужный компонент?

2020-10-14 22:08 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +  const CalcRating = (percent) =>{
Сразу импортировать в компонент

2020-10-14 22:09 UTC, AlexandrRumiantsev commented on src/components/app/app.jsx
> +      width: percent * 10 * 2 + '%'
Это объект для style в шаблоне

2020-10-14 22:10 UTC, AlexandrRumiantsev commented on src/components/app/app.jsx
> +  }
Создам src/helpers/CalcRating.js и  PremiumTemplate.js, далее внутри нужные функции, тогда куда их импортировать? Есть ли смысл в Аpp компонент, что бы потом через пропсы передовать? Или сразу импортировать в нужный компонент?

2020-10-14 22:10 UTC, AlexandrRumiantsev commented on src/components/app/app.jsx
> +  }
Возможно стоит оставить карту хардкодом? В задании не было сказано так делать. Тогда из моков фрейм убрать и эту функцию удалить?

2020-10-14 22:11 UTC, AlexandrRumiantsev commented on src/components/main/main.jsx
> +                        <span className="place-card__price-text">&#47;&nbsp;{offer.prices[1]}</span>
Могу оставить хардкодом night, но тут спорный момент, могут захотеть написать в других измерениях.

2020-10-14 22:11 UTC, AlexandrRumiantsev commented on src/mocks/offers.js
> +    meeter: {
Поменять host на meeter? Тут просто воспользовался переводчком)

2020-10-14 22:12 UTC, AlexandrRumiantsev commented on src/mocks/offers.js
> +  },
Как уже писал ранее, пока карту оставляем хардкодом, как была изначально и удаляю описание фреймов из моков?

2020-10-15 06:53 UTC, DmitryMarkov commented on src/components/main/main.jsx
> +                        <span className="place-card__price-text">&#47;&nbsp;{offer.prices[1]}</span>
Могут, но это в любом случае делается не так. Подумай, что будет если сайт мультиязычный? Лучше вернуть пока. Есть такие принципы разработки, с которыми очень советую ознакомиться: KISS и YAGNI
Попробуй применять их на проекте, не нарушая базовых критериев

2020-10-15 07:00 UTC, DmitryMarkov commented on src/mocks/offers.js
> +    meeter: {
> Поменять host на meeter? 

наоборот

2020-10-15 07:02 UTC, DmitryMarkov commented on src/mocks/offers.js
> +  },
все, что явно не прописано в задании, оставляем хардкодом. Карты будут в следующей теме

2020-10-15 07:02 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +  }
да

2020-10-15 07:05 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +  }
Сразу импортировать в компонент

2020-10-15 07:06 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +      width: percent * 10 * 2 + '%'
ок

2020-10-15 08:04 UTC, AlexandrRumiantsev commented on src/components/comments/comments.jsx
> +    data.rating = new FormData(formRef.current).get('rating');
Переделать компонент на управляемый

2020-10-15 08:06 UTC, AlexandrRumiantsev commented on src/components/comments/comments.jsx
> +    props.component.setState(
props.component.state.reviews.push(data) и props.component.setState( - Убрать

2020-10-15 08:07 UTC, AlexandrRumiantsev commented on src/components/comments/comments.jsx
> +    ).isRequired
Убрать из пропса передачу компонента, передать колбек и добавить в него заготовку для перерисовки чата.

2020-10-15 12:22 UTC, AlexandrRumiantsev commented on src/components/main/main.jsx
> +                      <img className="place-card__image" src={offer.gallary[0].src} width="260" height="200" alt="Place image"/>
Не понятно, что тут не так?

2020-10-15 23:10 UTC, AlexandrRumiantsev commented
Отчет по правкам.
1) Создал хелперы в папке src/helpers/ и убрал их из компонента App, далее импортировал в нужные компоненты. Функции называл с маленькой буквы.
2) Откатил карту в дефолтное состояние 
3) Переделал Comments из функционального компонента в классовый, убрал реф. Теперь это контролируемый компонент. и данные из него собираются по другому. 
4) Убрал обновление компонента и добавление комментариев, оставил колбек в компоненте room, в который передается рейтинг и текст комментария. Метод компонента comments, который передается в качестве колбека называется addComment
5) Убрал  компонент из пропса
7) В src/components/main/main.jsx просто добавить в <a href="#"> ссылку, правильно?
8) Убрал night из моковых данных.
9) Поменял meeter на host в моках
10) Убрал из моков фреймы карты, сау карту пока оставил хардкодом.
11) Убрал копипасту из comments.jsx. Заменил на рендер элемента в цикле.
12) Убрал конкатенацию, заменил на шаблонные строки в src/components/main/main.jsx
13) Сделал деструктуризацию offers в компоненте main

2020-10-16 21:05 UTC, DmitryMarkov reviewed
Всё ещё много недочетов, но основные пункты выполнены. ПРошу исправить в следующем PR.

2020-10-16 21:05 UTC, DmitryMarkov commented on src/components/comments/comments.jsx
> +    let index = this.state.titleInputs.length - number;
тот же вопрос

2020-10-16 21:05 UTC, DmitryMarkov commented on src/components/main/main.jsx
> +                      <img className="place-card__image" src={offer.gallary[0].src} width="260" height="200" alt="Place image"/>
опечатка

2020-10-16 21:05 UTC, DmitryMarkov commented on src/components/main/main.jsx
> +  offers: PropTypes.array.isRequired
заменить на arrayOf

2020-10-16 21:05 UTC, DmitryMarkov commented on src/components/room/room.jsx
> +                  (this.state.room.premium) ? premiumTemplate('property__mark') : ''
комнату не надо засовывать в стейт, брать из пропса

2020-10-16 21:05 UTC, DmitryMarkov commented on src/components/room/room.jsx
>    componentWillMount(){
Это я пропустил, но использование этого лайфхука недопустимо

2020-10-16 21:05 UTC, merged

2020-10-17 01:08 UTC, AlexandrRumiantsev commented on src/components/comments/comments.jsx
> +      titleInputs: [`terribly`, `badly`, `not bad`, `good`, `perfect`],
titleInputs сделать просто константой внутри компонента или её вынести куда то в другой файл?

2020-10-17 01:09 UTC, AlexandrRumiantsev commented on src/components/room/room.jsx
>    componentWillMount(){
Тут необходимо уточнить, что именно не так и самое главное почему?

2020-10-17 06:51 UTC, DmitryMarkov commented on src/components/comments/comments.jsx
> +      titleInputs: [`terribly`, `badly`, `not bad`, `good`, `perfect`],
Для начала константой ВНЕ компонента. потом можно вынести в отдельный файл, если будет переиспользоваться в других местах

2020-10-17 06:53 UTC, DmitryMarkov commented on src/components/room/room.jsx
>    componentWillMount(){
`componentWillMount` запрещен к использованию командой реакта и будет недоступен в новых версиях фреймворка. Лучше всегда найденные решения поверять в официальной документации, так как со временем старые подходы устаревают и появляются новые.

https://ru.reactjs.org/docs/react-component.html#unsafe_componentwillmount