Добавление динамиеской карты
htmlacademy-react/1521451-six-cities-5 pull request #7
Opened 2020-10-19 16:56 UTC by AlexandrRumiantsev

2020-10-19 22:12 UTC, DmitryMarkov requested changes
Задание выполнено с ошибками, просьба внести изменения согласно ДЗ

2020-10-19 22:12 UTC, DmitryMarkov commented on src/components/map/map.jsx
> +        zoomControl={true}
значения аттрибутов не соответствуют заданию

2020-10-19 22:12 UTC, DmitryMarkov commented on src/components/map/map.jsx
> +            <span>A pretty CSS3 popup. <br/> Easily customizable.</span>
Это явно не из домашнего задания

2020-10-19 22:12 UTC, DmitryMarkov commented on src/components/map/map.jsx
> +        }
Не соответствует заданию

2020-10-19 22:12 UTC, DmitryMarkov commented on src/components/map/map.jsx
> +    this.state = {
Чем оправдано использование state? Мы не вносим никаких изменений в эти значения, это просто начальная конфигурация

2020-10-20 07:57 UTC, AlexandrRumiantsev commented on package.json
> +    "css-loader": "^5.0.0",
Сама версия 5.0.0 верна? В документе не указана.

2020-10-20 07:58 UTC, AlexandrRumiantsev commented on src/components/map/map.jsx
> +    this.state = {
Разместить эти данные сверху в обычной константе?

2020-10-21 11:01 UTC, DmitryMarkov commented on package.json
> +    "css-loader": "^5.0.0",
Если работает, значит, проблем нет :)

2020-10-21 11:02 UTC, DmitryMarkov commented on src/components/map/map.jsx
> +    this.state = {
ну, например, пока так. Возможно, при смене города они будут приходить в компонент извне, но это вопрос для других заданий

2020-10-21 11:13 UTC, DmitryMarkov approved these changes
Замечания исправлены

2020-10-21 11:13 UTC, merged