Личный проект: больше подробностей (часть 2)
htmlacademy-react/1521451-six-cities-5 pull request #8
Opened 2020-10-21 18:38 UTC by AlexandrRumiantsev

2020-10-22 09:18 UTC, DmitryMarkov requested changes
1. необходимо исправить скрипт `eslint`, чтобы он правильно проверял файлы проекта (сейчас не проверяет) `"eslint --ext .jsx --ext .js src/"`
2. необходимо удалить папку `node_modules` и заново установить зависимости, при необходимости исправить, так как на моей машине проект не запускается.

![image](https://user-images.githubusercontent.com/9193608/96851450-b28e0580-1460-11eb-936d-ee6f5e4953c0.png)

2020-10-22 09:18 UTC, DmitryMarkov commented on src/components/offer-item/offer-item.jsx
> +                  <a href={'/offer/'+offer.id}>
конкатенация запрещена

2020-10-22 09:18 UTC, DmitryMarkov commented on src/components/offer-item/offer-item.jsx
> +                    <img className="place-card__image" src={offer.gallary[0].src} width="260" height="200" alt="Place image"/>
```suggestion
                    <img className="place-card__image" src={offer.gallery[0].src} width="260" height="200" alt="Place image"/>
```

2020-10-22 09:18 UTC, DmitryMarkov commented on src/components/offer-item/offer-item.jsx
> +  offer: PropTypes.array.isRequired
надо заменить на arrayOf здесь и далее с указанием содержания массива

2020-10-22 09:18 UTC, DmitryMarkov commented on src/components/reviews-item/reviews-item.jsx
> +           <time className="reviews__time" dateTime="2019-04-24">April 2019</time>
дата должна передаваться через пропсы

2020-10-22 09:18 UTC, DmitryMarkov commented on src/components/room/room.jsx
>    componentWillMount(){
Я говорил, что это хук надо заменить

2020-10-22 19:29 UTC, AlexandrRumiantsev commented on src/components/offer-item/offer-item.jsx
> +  offer: PropTypes.array.isRequired
Ранее уже писал, тут указание лектора + arrayOf не смогу так просто применить, разные данные приходят

2020-10-22 19:29 UTC, AlexandrRumiantsev commented on src/components/reviews-item/reviews-item.jsx
> +           <time className="reviews__time" dateTime="2019-04-24">April 2019</time>
2019-04-24 или April 2019?

2020-10-22 19:48 UTC, DmitryMarkov commented on src/components/reviews-item/reviews-item.jsx
> +           <time className="reviews__time" dateTime="2019-04-24">April 2019</time>
В моках должга быть дата или timestamp, а в шаблоне "человеческая", т.е. выглядеть должно также

2020-10-23 17:42 UTC, AlexandrRumiantsev commented
1) Исправил скрипт eslint и пофиксил все его замечания.
2) Убрал конкатенацию
3) Поменял gallary на gallery
4) Добавил arrayOf и везде доработал и применил шейпы.
5)  Дату передаю из моков в формате timestamp, написал функцию в хелперах, которая форматирует дату в нужный формат по макету.
6) Убрал хук componentWillMount, логику пока(скорее всего временно) перенес в конструктор, далее при необходимости могу убрать в отдельные методы. Но данные алгоритмы необходимы для формирования стейтов, поэтому пока в конструкторе.

2020-10-24 08:27 UTC, DmitryMarkov requested changes
1. Блок отзывов должен располагаться над формой добавления комментариев
2. Список предложений неподалеку должен отображать не более 3х предложений
3. Он не должен включать текущее предложение
![image](https://user-images.githubusercontent.com/9193608/97077364-cc0f8880-15eb-11eb-82f5-a0921114e4bd.png)

4. В форме комментария при выборе  рейтинга, предыдущие звезды должны тоже подсвечиваться (слева направо)
![image](https://user-images.githubusercontent.com/9193608/97077358-be5a0300-15eb-11eb-838e-002e7dde9f88.png)

5. Надо исправить ошибки в консоли
![image](https://user-images.githubusercontent.com/9193608/97077372-d893e100-15eb-11eb-983e-39d0047714df.png)
![image](https://user-images.githubusercontent.com/9193608/97077380-e21d4900-15eb-11eb-8da2-90084c0404ba.png)

2020-10-24 18:40 UTC, AlexandrRumiantsev commented
Вопрос: Допустим ли финт, реализованный в файле conmonent/offer-list/offer-list.js ?

2020-10-26 19:09 UTC, DmitryMarkov approved these changes
решение, конечно, костыльное, лучше переделать

2020-10-26 19:09 UTC, DmitryMarkov commented on src/components/offer-list/offer-list.jsx
> +      currentRoom: window.location.href.split(`/`)[4]
ну, конечно, так делать не стоит 🙂 
можно передавать currentOffer или его id и делать фильтрацию

2020-10-26 19:09 UTC, DmitryMarkov commented on src/components/offer-list/offer-list.jsx
> +        data.index++;
это тоже выглядит костыльно. Лучше все операции фильтрации сделать до передачи пропсов в компонент, а он пусть только выводит

2020-10-26 19:09 UTC, merged