Личный проект: контроль и ограничения (часть 1)
htmlacademy-react/1521451-six-cities-5 pull request #9
Opened 2020-10-27 15:18 UTC by AlexandrRumiantsev

2020-10-27 21:58 UTC, DmitryMarkov requested changes
Задание выполнено не полностью

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +        currentCity: newTitle,
зачем внутренний стейт если город хранится в редаксе?

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +  change(title) {
название не соответствует критерию

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +  change(title) {
методы класса надо биндить в конструкторе для корректной работы

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +                  <a onClick={
Вообще, мы роутер используем в проекте, поэтому здесь он тоже не помешал бы

2020-10-27 21:58 UTC, DmitryMarkov commented on src/helpers/filter-city.js
> +};
достаточно было поставить тернарник в `className` на `--active`

2020-10-27 21:58 UTC, DmitryMarkov commented on src/helpers/filter-city.js
> +  return filteredArr;
для этого есть метод массива filter

2020-10-27 21:58 UTC, DmitryMarkov commented on src/helpers/filter-city.js
> +const filterArrCities = (offers, current) => {
нет смысла выносить в хелперы то, что используется в одном только компоненте

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +        <div className="cities">
это и ниже не должно быть в компоненте "список городов"

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +              <MapCity offers={offers} />
Не выполнен пункт задания

> Не забудьте, что все отрисованные предложения, соответствующие отбору, также должны быть отрисованы на карте в виде пинов.

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +  currentCity: state.town,
почему в компоненте city, а в сторе - town?  Это же одно и то же, а вносит путаницу

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +    dispatch(ActionCreator.changeCity(titleCity, cb));
коллбек не нужен, если правильно реализовать логику компонента

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/offer-list/offer-list.jsx
> +                return (<OfferItem key={offer.id} offer={offer} />);
Не вижу разницы между 21й и 23-й строкой. Можешь объяснить?

2020-10-27 21:58 UTC, DmitryMarkov commented on src/components/offer-list/offer-list.jsx
> +                return (<OfferItem key={offer.id} offer={offer} />);
На странице соседних предложений из Гамбурга показываются предложения из Амстердама

2020-10-27 21:58 UTC, DmitryMarkov commented on src/helpers/filter-offers.js
> +};
как это работает и зачем?

2020-10-28 06:10 UTC, AlexandrRumiantsev commented on src/components/list-cities/list-cities.jsx
> +        currentCity: newTitle,
Тут я скорее храню начальное состояние(город отображающийся по дефолту)

2020-10-28 06:12 UTC, AlexandrRumiantsev commented on src/components/list-cities/list-cities.jsx
> +    dispatch(ActionCreator.changeCity(titleCity, cb));
Колбек я передаю, чтобы после изменения редакса, перерисовать лист сити, те обновить его состояние, как раз изменить тот самый дефолтный город.

2020-10-28 06:13 UTC, AlexandrRumiantsev commented on src/helpers/filter-offers.js
> +};
Тут  ограничиваю вывод 4 блоками в прочих предложениях и не ограничиваю для главной страницы, тк там один и тот же компонент.

2020-10-28 07:24 UTC, AlexandrRumiantsev commented on src/components/list-cities/list-cities.jsx
> +  change(title) {
Выполнил

2020-10-28 07:34 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +    dispatch(ActionCreator.changeCity(titleCity, cb));
Это не нужно. Реакт сам перерисует, если згачение в редаксе поменялось

2020-10-28 07:59 UTC, DmitryMarkov commented on src/components/list-cities/list-cities.jsx
> +        currentCity: newTitle,
Логику внутреннего стейта для выбранного горлда нужно убрать, она нарушает принцип единого источника правды

2020-11-01 16:46 UTC, AlexandrRumiantsev commented
Провел полный рефакторинг приложения
1) Все экраны приложения имеют постфикс -sreen, запросы к радаксу и статика - в контейнерах, логика - в компонентах.
2) Обращение в редаксу произвожу исключительно в контейнере, далее через пропсы передаю в компонент.
3) Убрал свою функцию для сохранения текущей страницы, использовал ту возможность реакта, которую обговаривали на консультации.
4) Почистил все не нужные вызовы.

2020-11-02 19:22 UTC, DmitryMarkov approved these changes
Проделана огромная работа и проект стал заметно лучше. Добавил несколько стилистических замечаний.

2020-11-02 19:22 UTC, DmitryMarkov commented on src/components/main-screen/components/filter.jsx
> +class Filter extends PureComponent {
всё-таки Filter - слишком общее название, оно предполагает, что других фильтров в приложении не будет. Лучше конкретизировать, что компонент собой представляет. Например, `SortBySelector` или ещё как-нибудь

2020-11-02 19:22 UTC, DmitryMarkov commented on src/components/main-screen/components/filter.jsx
> +    this.filterDOM.current.classList.toggle(`active`);
ну не надо через DOM работать, это вообще крайний случай. Используй state, например.

Тем более у меня оно все равно не работает как я ожидаю:
![image](https://user-images.githubusercontent.com/9193608/97908735-26c98280-1d58-11eb-9b9d-212f7173d1b0.png)

2020-11-02 19:22 UTC, DmitryMarkov commented on src/components/main-screen/components/filter.jsx
> +            <li onClick={this.filterChange} className="places__option" tabIndex="0">Top rated first</li>
лучше поставить один обработчик, почитай про Event Delegation https://learn.javascript.ru/event-delegation

2020-11-02 19:22 UTC, DmitryMarkov commented on src/components/main-screen/main-screen.jsx
> +  const filter = (param) ? param : currentCity;
скобки не нужны

2020-11-02 19:22 UTC, DmitryMarkov commented on src/components/main-screen/main-screen.jsx
> +  const curCity = (param) ? param : currentCity;
сокращения в именах нарушают базовый критерий

2020-11-02 19:22 UTC, DmitryMarkov commented on src/components/map/components/map-cities.jsx
> +    const zoom = 12;
значение лучше вынести в константу

2020-11-02 19:22 UTC, DmitryMarkov commented on src/components/offer/offer-container.jsx
> +        currentCity={currentCityRoom ? currentCityRoom : currentCity}
название `currentCityRoom` вводит в заблуждение, по смыслу будет правильней `currentRoomCity`

2020-11-02 19:22 UTC, DmitryMarkov commented on src/components/room-screen/room-screen.jsx
> +  const currentOffer = offers.filter((offer) => Number(offer.id) === Number(currentRoom))[0];
лучше использовать `Number.parseInt` с указанием радикса https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt

2020-11-02 19:22 UTC, DmitryMarkov commented on src/store/reducer.js
> +        case `Top rated first`:
лучше использовать не полнотекстовые значения (представь если на сайте будет многоязычность), а другие аттрибуты

2020-11-02 19:22 UTC, merged

2020-11-02 19:33 UTC, AlexandrRumiantsev commented on src/components/main-screen/main-screen.jsx
> +  const filter = (param) ? param : currentCity;
Тут требует линтер) при npm test